# Generated by Django 3.2.3 on 2023-08-18 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationcode',
            name='authorization_code',
            field=models.IntegerField(blank=True, error_messages={'validators': 'Код авторизации должен быть от 0 до 9999'}, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='activated_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
